/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/token/jwt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Jwt */
    get: operations['jwt_api_v1_token_jwt_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Tokens */
    get: operations['list_tokens_api_v1_token_get'];
    put?: never;
    /** Create */
    post: operations['create_api_v1_token_post'];
    /** Delete By Name */
    delete: operations['delete_by_name_api_v1_token_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/token/rotate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Rotate */
    put: operations['rotate_api_v1_token_rotate_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/token/attestation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Attestation */
    patch: operations['attestation_api_v1_token_attestation_patch'];
    trace?: never;
  };
  '/api/v1/token/{token_value}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete By Value */
    delete: operations['delete_by_value_api_v1_token__token_value__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/latest/token/jwt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Jwt */
    get: operations['jwt_api_latest_token_jwt_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/latest/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Tokens */
    get: operations['list_tokens_api_latest_token_get'];
    put?: never;
    /** Create */
    post: operations['create_api_latest_token_post'];
    /** Delete By Name */
    delete: operations['delete_by_name_api_latest_token_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/latest/token/rotate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Rotate */
    put: operations['rotate_api_latest_token_rotate_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/latest/token/attestation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Attestation */
    patch: operations['attestation_api_latest_token_attestation_patch'];
    trace?: never;
  };
  '/api/latest/token/{token_value}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete By Value */
    delete: operations['delete_by_value_api_latest_token__token_value__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/.well-known/jwks.json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Jwks */
    get: operations['_jwks__well_known_jwks_json_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/mfa/jwt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Jwt
     * @description Get a jwt for the user that authenticated via MFA and start a session.
     *
     *     The session in this case is a special token roughly linked to an auth
     *     session. This session token is then used to generate subtokens that
     *     are linked to the lifetime of the auth session.
     *
     *     The lifetime of this session token remains set from its initialization.
     *     If the session is expired when this API is called, it is refreshed.
     */
    get: operations['jwt_api_v1_mfa_jwt_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/latest/mfa/jwt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Jwt
     * @description Get a jwt for the user that authenticated via MFA and start a session.
     *
     *     The session in this case is a special token roughly linked to an auth
     *     session. This session token is then used to generate subtokens that
     *     are linked to the lifetime of the auth session.
     *
     *     The lifetime of this session token remains set from its initialization.
     *     If the session is expired when this API is called, it is refreshed.
     */
    get: operations['jwt_api_latest_mfa_jwt_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** JWKSet */
    JWKSet: {
      /**
       * Keys
       * @default []
       */
      keys: Record<string, unknown>[] | null;
    };
    /** JWTResponse */
    JWTResponse: {
      /** Jwt */
      jwt: string;
    };
    /** Token */
    Token: {
      /** Name */
      name: string;
      /** Id */
      id?: string | null;
      /** Iat */
      iat?: number | null;
      /** Nbf */
      nbf?: number | null;
      /** Exp */
      exp?: number | null;
      /**
       * Paths
       * @default []
       */
      paths: string[] | null;
      /**
       * Scopes
       * @default []
       */
      scopes: string[] | null;
      /**
       * Rotatable
       * @default false
       */
      rotatable: boolean | null;
    };
    /** TokenRotationRequest */
    TokenRotationRequest: {
      /** Ids */
      ids: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  jwt_api_v1_token_jwt_get: {
    parameters: {
      query?: never;
      header: {
        'x-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['JWTResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_tokens_api_v1_token_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['Token'][];
        };
      };
    };
  };
  create_api_v1_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['Token'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: Record<string, unknown>;
        content: {
          'application/json': string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_by_name_api_v1_token_delete: {
    parameters: {
      query: {
        /** @description Name of the token to delete */
        name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  rotate_api_v1_token_rotate_put: {
    parameters: {
      query?: {
        /** @description Requested token lifetime in days (max: configured max_lifetime) */
        exp_days?: number | null;
      };
      header: {
        'x-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  attestation_api_v1_token_attestation_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenRotationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_by_value_api_v1_token__token_value__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token_value: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  jwt_api_latest_token_jwt_get: {
    parameters: {
      query?: never;
      header: {
        'x-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['JWTResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_tokens_api_latest_token_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['Token'][];
        };
      };
    };
  };
  create_api_latest_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['Token'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: Record<string, unknown>;
        content: {
          'application/json': string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_by_name_api_latest_token_delete: {
    parameters: {
      query: {
        /** @description Name of the token to delete */
        name: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  rotate_api_latest_token_rotate_put: {
    parameters: {
      query?: {
        /** @description Requested token lifetime in days (max: configured max_lifetime) */
        exp_days?: number | null;
      };
      header: {
        'x-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  attestation_api_latest_token_attestation_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenRotationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_by_value_api_latest_token__token_value__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token_value: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  _jwks__well_known_jwks_json_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['JWKSet'];
        };
      };
    };
  };
  jwt_api_v1_mfa_jwt_get: {
    parameters: {
      query?: never;
      header: {
        'x-auth-request-access-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['JWTResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  jwt_api_latest_mfa_jwt_get: {
    parameters: {
      query?: never;
      header: {
        'x-auth-request-access-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['JWTResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
