/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/jwt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Jwt */
    post: operations['_jwt_api_v1_jwt_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/latest/jwt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Jwt */
    post: operations['_jwt_api_latest_jwt_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/.well-known/jwks.json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Jwks */
    get: operations['_jwks__well_known_jwks_json_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/community': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List */
    get: operations['_list_api_v1_community_get'];
    put?: never;
    /** Create */
    post: operations['create_api_v1_community_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/community/{id_or_name}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get */
    get: operations['get_api_v1_community__id_or_name__get'];
    put?: never;
    post?: never;
    /** Remove */
    delete: operations['remove_api_v1_community__id_or_name__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/community/{community_id}/route/{route_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Add Route */
    put: operations['add_route_api_v1_community__community_id__route__route_id__put'];
    post?: never;
    /** Remove From Community */
    delete: operations['remove_from_community_api_v1_community__community_id__route__route_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/latest/community': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List */
    get: operations['_list_api_latest_community_get'];
    put?: never;
    /** Create */
    post: operations['create_api_latest_community_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/latest/community/{id_or_name}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get */
    get: operations['get_api_latest_community__id_or_name__get'];
    put?: never;
    post?: never;
    /** Remove */
    delete: operations['remove_api_latest_community__id_or_name__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/latest/community/{community_id}/route/{route_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Add Route */
    put: operations['add_route_api_latest_community__community_id__route__route_id__put'];
    post?: never;
    /** Remove From Community */
    delete: operations['remove_from_community_api_latest_community__community_id__route__route_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/route': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Available */
    get: operations['list_available_api_v1_route_get'];
    put?: never;
    /** Register */
    post: operations['register_api_v1_route_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/route/hello-world': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Hello */
    get: operations['hello_api_v1_route_hello_world_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v2/route': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Available */
    get: operations['list_available_api_v2_route_get'];
    put?: never;
    /** Register */
    post: operations['register_api_v2_route_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v2/route/hello-world': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Hello */
    get: operations['hello_api_v2_route_hello_world_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/latest/route': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Available */
    get: operations['list_available_api_latest_route_get'];
    put?: never;
    /** Register */
    post: operations['register_api_latest_route_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/latest/route/hello-world': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Hello */
    get: operations['hello_api_latest_route_hello_world_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Airlock */
    Airlock: {
      /** Jwt Issuer Url */
      jwt_issuer_url?: string | null;
    };
    /** Community */
    Community: {
      /** Name */
      name: string;
      /** Id */
      id?: string | null;
      /**
       * Routes
       * @default []
       */
      routes: unknown[] | null;
    };
    /** EntitySet */
    EntitySet: {
      /**
       * Users
       * @default []
       */
      users: string[] | null;
      /**
       * Groups
       * @default []
       */
      groups: string[] | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** JWKSet */
    JWKSet: {
      /**
       * Keys
       * @default []
       */
      keys: Record<string, unknown>[] | null;
    };
    /** MembershipRequest */
    MembershipRequest: {
      /** Entity Id */
      entity_id?: string | null;
      /** Community Id */
      community_id?: string | null;
      /** Route Id */
      route_id?: string | null;
      /** Status */
      status?: string | null;
    };
    /** RegistrationRequest */
    RegistrationRequest: {
      /** Name */
      name: string;
      /** Domain Name */
      domain_name?: string | null;
      /** Community Name */
      community_name?: string | null;
    };
    /** RegistrationResponse */
    RegistrationResponse: {
      /** Url */
      url: string;
      airlock: components['schemas']['Airlock'];
      tunnel: components['schemas']['Tunnel'];
      /** Endpoint */
      endpoint?: string | null;
      /** Jwt */
      jwt?: string | null;
    };
    /** Route */
    Route: {
      /** Name */
      name: string;
      /** Domain Name */
      domain_name?: string | null;
      /** Community Name */
      community_name?: string | null;
      /** Id */
      id?: string | null;
      /** Dst */
      dst?: string | null;
      /** Src */
      src?: string | null;
      /** Url */
      url?: string | null;
      /** Token */
      token?: string | null;
      /** Endpoint */
      endpoint?: string | null;
      /** Jwt */
      jwt?: string | null;
      /** Community Id */
      community_id?: string | null;
      /**
       * @default {
       *       "allowed": {
       *         "groups": [],
       *         "users": []
       *       },
       *       "disallowed": {
       *         "groups": [],
       *         "users": []
       *       }
       *     }
       */
      rules: components['schemas']['Rules'] | null;
    };
    /** Rules */
    Rules: {
      /** Version */
      version?: string | null;
      /**
       * @default {
       *       "users": [],
       *       "groups": []
       *     }
       */
      allowed: components['schemas']['EntitySet'] | null;
      /**
       * @default {
       *       "users": [],
       *       "groups": []
       *     }
       */
      disallowed: components['schemas']['EntitySet'] | null;
    };
    /** Tunnel */
    Tunnel: {
      /** Url */
      url?: string | null;
      /** Jwt */
      jwt?: string | null;
      /** Endpoint */
      endpoint?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  _jwt_api_v1_jwt_post: {
    parameters: {
      query?: never;
      header: {
        'x-jwt': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': Record<string, unknown>;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  _jwt_api_latest_jwt_post: {
    parameters: {
      query?: never;
      header: {
        'x-jwt': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': Record<string, unknown>;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  _jwks__well_known_jwks_json_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['JWKSet'];
        };
      };
    };
  };
  _list_api_v1_community_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['Community'][];
        };
      };
    };
  };
  create_api_v1_community_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Community'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['Community'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_api_v1_community__id_or_name__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id_or_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['Community'] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_api_v1_community__id_or_name__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id_or_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_route_api_v1_community__community_id__route__route_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        community_id: string;
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['MembershipRequest'] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_from_community_api_v1_community__community_id__route__route_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        community_id: string;
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  _list_api_latest_community_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['Community'][];
        };
      };
    };
  };
  create_api_latest_community_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Community'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['Community'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_api_latest_community__id_or_name__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id_or_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['Community'] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_api_latest_community__id_or_name__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id_or_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_route_api_latest_community__community_id__route__route_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        community_id: string;
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['MembershipRequest'] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_from_community_api_latest_community__community_id__route__route_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        community_id: string;
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_available_api_v1_route_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['Route'][];
        };
      };
    };
  };
  register_api_v1_route_post: {
    parameters: {
      query?: never;
      header: {
        'x-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegistrationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['RegistrationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  hello_api_v1_route_hello_world_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  list_available_api_v2_route_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['Route'][];
        };
      };
    };
  };
  register_api_v2_route_post: {
    parameters: {
      query?: never;
      header: {
        'x-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegistrationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['RegistrationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  hello_api_v2_route_hello_world_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  list_available_api_latest_route_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['Route'][];
        };
      };
    };
  };
  register_api_latest_route_post: {
    parameters: {
      query?: never;
      header: {
        'x-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegistrationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['RegistrationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  hello_api_latest_route_hello_world_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: Record<string, unknown>;
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
