apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "piko.fullname" . }}
  labels:
    {{- include "piko.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "piko.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "piko.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.global.serviceAccount.name | default "default" }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: piko
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            {{- if .Values.args }}
            {{- toYaml .Values.args | nindent 12 }}
            {{- else }}
            - server
            - --config.path
            - /config/server.yaml
            - --config.expand-env
            {{- end }}
          ports:
            - name: proxy
              containerPort: {{ .Values.server.proxyPort }}
              protocol: TCP
            - name: upstream
              containerPort: {{ .Values.server.upstreamPort }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.server.adminPort }}
              protocol: TCP
            - name: gossip
              containerPort: {{ .Values.server.gossipPort }}
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "piko.fullname" . }}
            items:
            - key: "server.yaml"
              path: "server.yaml"
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
