apiVersion: v1
kind: Service
metadata:
  name: {{ include "piko.fullname" . }}
  labels:
    {{- include "piko.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.server.proxyPort }}
      targetPort: proxy
      protocol: TCP
      name: proxy
    - port: {{ .Values.server.upstreamPort }}
      targetPort: upstream
      protocol: TCP
      name: upstream
    - port: {{ .Values.server.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
    - port: {{ .Values.server.gossipPort }}
      targetPort: gossip
      protocol: TCP
      name: gossip
  selector:
    {{- include "piko.selectorLabels" . | nindent 4 }}
