{{- if not .Values.dependencies.rabbitmq.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "route-registry.rabbitmqSecretName" . }}
  labels:
    {{- include "route-registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  rabbitmq-username: {{ .Values.dependencies.rabbitmq.username | quote }}
  rabbitmq-password: {{ .Values.dependencies.rabbitmq.password | quote }}
{{- end }}
