apiVersion: v2
name: wormhole
description: Consolidated Helm chart for deploying the Wormhole platform.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  # Third-party dependencies
  - name: nats
    version: 1.2.7
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nats.enabled
  - name: oauth2-proxy
    version: 7.8.0
    repository: "https://oauth2-proxy.github.io/manifests"
    condition: oauth2-proxy.enabled

  # Internal dependencies
  - name: holepunch
    version: 0.1.0
    condition: holepunch.enabled
  - name: piko
    version: 0.1.0
    condition: piko.enabled
  - name: postgres
    version: 0.1.0
    condition: postgres.enabled
  - name: rabbitmq
    version: 0.1.0
    condition: rabbitmq.enabled
  - name: route-registry
    version: 0.1.0
    condition: route-registry.enabled
  - name: token-service
    version: 0.1.0
    condition: token-service.enabled
